export const ADD_EXPENSE = "ADD_EXPENSE";
export const EDIT_EXPENSE = "EDIT_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const FETCH_EXPENSES = "FETCH_EXPENSES";
export const EXPENSES_LOADED = "EXPENSES_LOADED";
export const EXPENSES_LOAD_FAILED = "EXPENSES_LOAD_FAILED";
